import type {
  Company,
  Department,
  Employee,
  Equipment,
  AssignmentHistory,
} from "./types"

export const mockCompany: Company = {
  id: "company-1",
  name: "Acme Corporation",
  createdAt: "2024-01-15T00:00:00Z",
}

export const mockDepartments: Department[] = [
  {
    id: "dept-1",
    companyId: "company-1",
    name: "Information Technology",
    description: "IT infrastructure and software development",
  },
  {
    id: "dept-2",
    companyId: "company-1",
    name: "Operations",
    description: "Day-to-day business operations",
  },
  {
    id: "dept-3",
    companyId: "company-1",
    name: "Warehouse",
    description: "Inventory and logistics management",
  },
  {
    id: "dept-4",
    companyId: "company-1",
    name: "Maintenance",
    description: "Equipment maintenance and repairs",
  },
]

export const mockEmployees: Employee[] = [
  {
    id: "emp-1",
    companyId: "company-1",
    departmentId: "dept-1",
    name: "Sarah Chen",
    position: "Senior Developer",
    email: "sarah.chen@acme.com",
    status: "active",
  },
  {
    id: "emp-2",
    companyId: "company-1",
    departmentId: "dept-1",
    name: "Marcus Johnson",
    position: "IT Support Lead",
    email: "marcus.johnson@acme.com",
    status: "active",
  },
  {
    id: "emp-3",
    companyId: "company-1",
    departmentId: "dept-2",
    name: "Emily Rodriguez",
    position: "Operations Manager",
    email: "emily.rodriguez@acme.com",
    status: "active",
  },
  {
    id: "emp-4",
    companyId: "company-1",
    departmentId: "dept-2",
    name: "David Kim",
    position: "Business Analyst",
    email: "david.kim@acme.com",
    status: "active",
  },
  {
    id: "emp-5",
    companyId: "company-1",
    departmentId: "dept-3",
    name: "James Wilson",
    position: "Warehouse Supervisor",
    email: "james.wilson@acme.com",
    status: "active",
  },
  {
    id: "emp-6",
    companyId: "company-1",
    departmentId: "dept-3",
    name: "Maria Santos",
    position: "Logistics Coordinator",
    email: "maria.santos@acme.com",
    status: "active",
  },
  {
    id: "emp-7",
    companyId: "company-1",
    departmentId: "dept-4",
    name: "Robert Taylor",
    position: "Maintenance Technician",
    email: "robert.taylor@acme.com",
    status: "active",
  },
  {
    id: "emp-8",
    companyId: "company-1",
    departmentId: "dept-4",
    name: "Lisa Anderson",
    position: "Equipment Specialist",
    email: "lisa.anderson@acme.com",
    status: "inactive",
  },
]

export const mockEquipment: Equipment[] = [
  {
    id: "equip-1",
    companyId: "company-1",
    name: 'MacBook Pro 16"',
    brand: "Apple",
    serialNumber: "C02XL1Q6JG5L",
    purchaseDate: "2024-01-10",
    purchasePrice: 2499,
    warrantyMonths: 24,
    departmentId: "dept-1",
    assignedEmployeeId: "emp-1",
    status: "assigned",
    notes: "Development laptop",
  },
  {
    id: "equip-2",
    companyId: "company-1",
    name: 'MacBook Pro 14"',
    brand: "Apple",
    serialNumber: "C02XL1Q7JG5M",
    purchaseDate: "2024-02-15",
    purchasePrice: 1999,
    warrantyMonths: 24,
    departmentId: "dept-1",
    assignedEmployeeId: "emp-2",
    status: "assigned",
  },
  {
    id: "equip-3",
    companyId: "company-1",
    name: "ThinkPad X1 Carbon",
    brand: "Lenovo",
    serialNumber: "PF2ABCD1",
    purchaseDate: "2023-08-20",
    purchasePrice: 1599,
    warrantyMonths: 36,
    departmentId: "dept-2",
    assignedEmployeeId: "emp-3",
    status: "assigned",
  },
  {
    id: "equip-4",
    companyId: "company-1",
    name: "ThinkPad X1 Carbon",
    brand: "Lenovo",
    serialNumber: "PF2ABCD2",
    purchaseDate: "2023-08-20",
    purchasePrice: 1599,
    warrantyMonths: 36,
    departmentId: "dept-2",
    status: "available",
  },
  {
    id: "equip-5",
    companyId: "company-1",
    name: "Forklift Model 250",
    brand: "Toyota",
    serialNumber: "TFL-2024-001",
    purchaseDate: "2023-06-01",
    purchasePrice: 25000,
    warrantyMonths: 12,
    maintenanceIntervalMonths: 3,
    departmentId: "dept-3",
    assignedEmployeeId: "emp-5",
    status: "assigned",
    notes: "Primary warehouse forklift",
  },
  {
    id: "equip-6",
    companyId: "company-1",
    name: "Forklift Model 150",
    brand: "Toyota",
    serialNumber: "TFL-2024-002",
    purchaseDate: "2023-07-15",
    purchasePrice: 18000,
    warrantyMonths: 12,
    maintenanceIntervalMonths: 3,
    departmentId: "dept-3",
    status: "maintenance",
    notes: "Scheduled maintenance - brake inspection",
  },
  {
    id: "equip-7",
    companyId: "company-1",
    name: "Power Drill Set",
    brand: "DeWalt",
    serialNumber: "DW-2024-101",
    purchaseDate: "2024-01-05",
    purchasePrice: 450,
    departmentId: "dept-4",
    assignedEmployeeId: "emp-7",
    status: "assigned",
  },
  {
    id: "equip-8",
    companyId: "company-1",
    name: "Industrial Welder",
    brand: "Lincoln",
    serialNumber: "LW-2023-042",
    purchaseDate: "2023-03-10",
    purchasePrice: 3500,
    warrantyMonths: 24,
    maintenanceIntervalMonths: 6,
    departmentId: "dept-4",
    status: "damaged",
    notes: "Power supply issue - awaiting repair",
  },
  {
    id: "equip-9",
    companyId: "company-1",
    name: 'Monitor 27" 4K',
    brand: "Dell",
    serialNumber: "DELL-MON-001",
    purchaseDate: "2024-02-01",
    purchasePrice: 549,
    warrantyMonths: 36,
    departmentId: "dept-1",
    assignedEmployeeId: "emp-1",
    status: "assigned",
  },
  {
    id: "equip-10",
    companyId: "company-1",
    name: 'Monitor 27" 4K',
    brand: "Dell",
    serialNumber: "DELL-MON-002",
    purchaseDate: "2024-02-01",
    purchasePrice: 549,
    warrantyMonths: 36,
    departmentId: "dept-1",
    status: "available",
  },
  {
    id: "equip-11",
    companyId: "company-1",
    name: "Barcode Scanner",
    brand: "Zebra",
    serialNumber: "ZBS-2024-001",
    purchaseDate: "2024-03-01",
    purchasePrice: 299,
    warrantyMonths: 12,
    departmentId: "dept-3",
    assignedEmployeeId: "emp-6",
    status: "assigned",
  },
  {
    id: "equip-12",
    companyId: "company-1",
    name: "Barcode Scanner",
    brand: "Zebra",
    serialNumber: "ZBS-2024-002",
    purchaseDate: "2024-03-01",
    purchasePrice: 299,
    warrantyMonths: 12,
    departmentId: "dept-3",
    status: "lost",
    notes: "Last seen in storage area B",
  },
  {
    id: "equip-13",
    companyId: "company-1",
    name: "Projector",
    brand: "Epson",
    serialNumber: "EPS-PRJ-001",
    purchaseDate: "2023-11-15",
    purchasePrice: 899,
    warrantyMonths: 24,
    departmentId: "dept-2",
    status: "available",
    notes: "Conference room projector",
  },
  {
    id: "equip-14",
    companyId: "company-1",
    name: "Safety Harness Kit",
    brand: "3M",
    serialNumber: "3M-SH-2024-01",
    purchaseDate: "2024-01-20",
    purchasePrice: 350,
    maintenanceIntervalMonths: 12,
    departmentId: "dept-4",
    status: "available",
  },
  {
    id: "equip-15",
    companyId: "company-1",
    name: "Wireless Keyboard & Mouse",
    brand: "Logitech",
    serialNumber: "LOG-KM-001",
    purchaseDate: "2024-02-10",
    purchasePrice: 129,
    warrantyMonths: 24,
    departmentId: "dept-1",
    assignedEmployeeId: "emp-2",
    status: "assigned",
  },
]

export const mockAssignmentHistory: AssignmentHistory[] = [
  {
    id: "hist-1",
    equipmentId: "equip-1",
    employeeId: "emp-1",
    employeeName: "Sarah Chen",
    departmentId: "dept-1",
    departmentName: "Information Technology",
    assignedDate: "2024-01-15",
    conditionWhenAssigned: "New",
    notes: "Initial assignment",
  },
  {
    id: "hist-2",
    equipmentId: "equip-2",
    employeeId: "emp-2",
    employeeName: "Marcus Johnson",
    departmentId: "dept-1",
    departmentName: "Information Technology",
    assignedDate: "2024-02-20",
    conditionWhenAssigned: "New",
  },
  {
    id: "hist-3",
    equipmentId: "equip-3",
    employeeId: "emp-3",
    employeeName: "Emily Rodriguez",
    departmentId: "dept-2",
    departmentName: "Operations",
    assignedDate: "2023-09-01",
    conditionWhenAssigned: "New",
  },
  {
    id: "hist-4",
    equipmentId: "equip-5",
    employeeId: "emp-5",
    employeeName: "James Wilson",
    departmentId: "dept-3",
    departmentName: "Warehouse",
    assignedDate: "2023-06-15",
    conditionWhenAssigned: "New",
    notes: "Primary operator",
  },
  {
    id: "hist-5",
    equipmentId: "equip-7",
    employeeId: "emp-7",
    employeeName: "Robert Taylor",
    departmentId: "dept-4",
    departmentName: "Maintenance",
    assignedDate: "2024-01-10",
    conditionWhenAssigned: "New",
  },
  {
    id: "hist-6",
    equipmentId: "equip-9",
    employeeId: "emp-1",
    employeeName: "Sarah Chen",
    departmentId: "dept-1",
    departmentName: "Information Technology",
    assignedDate: "2024-02-05",
    conditionWhenAssigned: "New",
  },
  {
    id: "hist-7",
    equipmentId: "equip-11",
    employeeId: "emp-6",
    employeeName: "Maria Santos",
    departmentId: "dept-3",
    departmentName: "Warehouse",
    assignedDate: "2024-03-05",
    conditionWhenAssigned: "New",
  },
  {
    id: "hist-8",
    equipmentId: "equip-15",
    employeeId: "emp-2",
    employeeName: "Marcus Johnson",
    departmentId: "dept-1",
    departmentName: "Information Technology",
    assignedDate: "2024-02-15",
    conditionWhenAssigned: "New",
  },
  {
    id: "hist-9",
    equipmentId: "equip-4",
    employeeId: "emp-4",
    employeeName: "David Kim",
    departmentId: "dept-2",
    departmentName: "Operations",
    assignedDate: "2023-09-15",
    returnedDate: "2024-01-10",
    conditionWhenAssigned: "New",
    conditionWhenReturned: "Good",
    notes: "Returned - switched to desktop",
  },
  {
    id: "hist-10",
    equipmentId: "equip-8",
    employeeId: "emp-7",
    employeeName: "Robert Taylor",
    departmentId: "dept-4",
    departmentName: "Maintenance",
    assignedDate: "2023-04-01",
    returnedDate: "2024-02-28",
    conditionWhenAssigned: "Good",
    conditionWhenReturned: "Damaged",
    notes: "Power supply failure during operation",
  },
]
